
CREATE TABLE `ascApp` (
  `idascApp` int(11) NOT NULL AUTO_INCREMENT,
  `AppName` varchar(100) DEFAULT NULL,
  `AppDisplayVal` varchar(500) DEFAULT NULL,
  `AppDisplaySort` int(11) DEFAULT NULL,
  `AppIsRelease` varchar(1) DEFAULT NULL,
  `AppReleaseDate` datetime DEFAULT NULL,
  `AppPrefix` varchar(10) DEFAULT NULL,
  `AppDesc` varchar(500) DEFAULT NULL,
  `AppKey` varchar(45) NOT NULL,
  `AppVer` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`idascApp`),
  UNIQUE KEY `idASCApp_UNIQUE` (`idascApp`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascApp_User` (
  `idascApp_User` int(11) NOT NULL AUTO_INCREMENT,
  `AppName` varchar(100) DEFAULT NULL,
  `AppKey` varchar(45) NOT NULL,
  `asc_userKey` varchar(45) NOT NULL,
  `asc_userID` varchar(100) NOT NULL,
  `AppUser_Enable` bit(1) NOT NULL,
  `AppUser_EnableDate` datetime NOT NULL,
  `AppUser_DisableDate` datetime DEFAULT NULL,
  PRIMARY KEY (`idascApp_User`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_DailyACPRank_NBA_2018_s1` (
  `idascFanta_DailyACPRank_NBA_2018_s1` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_mDate_est` date DEFAULT NULL,
  `ascFanta_mDate_hkt` date DEFAULT NULL,
  `ascFanta_pID` int(11) DEFAULT NULL,
  `ascFanta_gPos` varchar(20) DEFAULT NULL,
  `ascFanta_TACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_pValue` decimal(5,2) DEFAULT NULL,
  `ascFanta_Acm_pts` int(11) DEFAULT '0',
  `ascFanta_Acm_ast` int(11) DEFAULT '0',
  `ascFanta_Acm_reb` int(11) DEFAULT '0',
  `ascFanta_Acm_stl` int(11) DEFAULT '0',
  `ascFanta_Acm_blk` int(11) DEFAULT '0',
  `ascFanta_Acm_tos` int(11) DEFAULT '0',
  `ascFanta_Acm_fgs` int(11) DEFAULT '0',
  `ascFanta_Acm_fts` int(11) DEFAULT '0',
  `ascFanta_Acm_tdb` int(11) DEFAULT '0',
  `ascFanta_Acm_gmPlayed` int(11) DEFAULT '0',
  `ascFanta_Acm_min` varchar(45) DEFAULT NULL,
  `ascFanta_AACP` decimal(6,2) DEFAULT '0.00',
  `ascFanta_rStatus` varchar(50) DEFAULT NULL,
  `ascFanta_lastUpDate` datetime DEFAULT NULL,
  `ascFanta_ODDate` datetime DEFAULT NULL,
  PRIMARY KEY (`idascFanta_DailyACPRank_NBA_2018_s1`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_DailyACPRank_NBA_2018_s2` (
  `idascFanta_DailyACPRank_NBA_2018` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_mDate_est` date DEFAULT NULL,
  `ascFanta_mDate_hkt` date DEFAULT NULL,
  `ascFanta_pID` int(11) DEFAULT NULL,
  `ascFanta_gPos` varchar(20) DEFAULT NULL,
  `ascFanta_TACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_pValue` decimal(5,2) DEFAULT NULL,
  `ascFanta_Acm_pts` int(11) DEFAULT '0',
  `ascFanta_Acm_ast` int(11) DEFAULT '0',
  `ascFanta_Acm_reb` int(11) DEFAULT '0',
  `ascFanta_Acm_stl` int(11) DEFAULT '0',
  `ascFanta_Acm_blk` int(11) DEFAULT '0',
  `ascFanta_Acm_tos` int(11) DEFAULT '0',
  `ascFanta_Acm_fgs` int(11) DEFAULT '0',
  `ascFanta_Acm_fts` int(11) DEFAULT '0',
  `ascFanta_Acm_tdb` int(11) DEFAULT '0',
  `ascFanta_Acm_gmPlayed` int(11) DEFAULT '0',
  `ascFanta_Acm_min` varchar(45) DEFAULT NULL,
  `ascFanta_AACP` decimal(6,2) DEFAULT '0.00',
  `ascFanta_rStatus` varchar(50) DEFAULT NULL,
  `ascFanta_lastUpDate` datetime DEFAULT NULL,
  `ascFanta_ODDate` datetime DEFAULT NULL,
  PRIMARY KEY (`idascFanta_DailyACPRank_NBA_2018`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_DailyTimeSegment_NBA` (
  `idascFanta_DailyTimeSegment_NBA` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_dayStart_est` datetime DEFAULT NULL,
  `ascFanta_dayStart_hkt` datetime DEFAULT NULL,
  `ascFanta_dayEnd_est` datetime DEFAULT NULL,
  `ascFanta_dayEnd_hkt` datetime DEFAULT NULL,
  `ascFanta_League` varchar(45) DEFAULT NULL,
  `ascFanta_seasonYear` varchar(45) DEFAULT NULL,
  `ascFanta_seasonStage` varchar(45) DEFAULT NULL,
  `ascFanta_BuyTrade` int(11) DEFAULT '1',
  `ascFanta_BuyCost` int(11) DEFAULT '1',
  `ascFanta_RCR_Window` int(11) DEFAULT '0',
  `ascFanta_RCR_EndTime_est` datetime DEFAULT NULL,
  `ascFanta_RCR_EndTime_hkt` datetime DEFAULT NULL,
  `ascFanta_RCRManual_EndTime_est` datetime DEFAULT NULL,
  `ascFanta_RCRManual_EndTime_hkt` datetime DEFAULT NULL,
  `ascFanta_UTRosterCopy_StartTime_est` datetime DEFAULT NULL,
  `ascFanta_UTRosterCopy_StartTime_hkt` datetime DEFAULT NULL,
  `ascFanta_UTRosterCopy_Status` int(11) DEFAULT '0',
  `ascFanta_RosterValueCalculation_Status` int(11) DEFAULT '0',
  `ascFanta_TodayMatches` varchar(500) DEFAULT NULL,
  `ascFanta_GameResults` varchar(500) DEFAULT NULL,
  `ascFanta_GameResult_Status` int(11) DEFAULT '0',
  `ascFanta_ACPCalculation` varchar(500) DEFAULT NULL,
  `ascFanta_ACPCalculation_Status` int(11) DEFAULT '0',
  `ascFanta_FreeTradeKey` varchar(36) DEFAULT NULL,
  `ascFanta_FreeTradeValue` int(11) DEFAULT NULL,
  `ascFanta_FreeTrade_Timestamp` datetime DEFAULT NULL,
  `ascFanta_PlayerMovement_StartTime_est` datetime DEFAULT NULL,
  `ascFanta_PlayerMovement_StartTime_hkt` datetime DEFAULT NULL,
  `ascFanta_PlayerMovement_Status` int(11) DEFAULT '0',
  `ascFanta_MatchMovement_StartTime_est` datetime DEFAULT NULL,
  `ascFanta_MatchMovement_StartTime_hkt` datetime DEFAULT NULL,
  `ascFanta_MatchMovement_Status` int(11) DEFAULT '0',
  `ascFanta_DayComplete` int(11) DEFAULT '0',
  `ascFanta_recordKey` varchar(36) DEFAULT NULL,
  `ascFanta_TimeZone` varchar(45) DEFAULT NULL,
  `ascFanta_rActive` int(11) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_DailyTimeSegment_NBA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_DailyValueRank_NBA_2018_s1` (
  `idascFanta_DailyValueRank_NBA_2018_s1` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_mDate_est` date DEFAULT NULL,
  `ascFanta_mDate_hkt` date DEFAULT NULL,
  `ascFanta_mDate` varchar(45) DEFAULT NULL,
  `ascFanta_pID` int(11) DEFAULT NULL,
  `ascFanta_gPos` varchar(20) DEFAULT NULL,
  `ascFanta_TodayAvgACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_TACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_TodayGain` int(11) DEFAULT '0',
  `ascFanta_TodayLoss` int(11) DEFAULT '0',
  `ascFanta_TodayTTx` int(11) DEFAULT '0',
  `ascFanta_TodayTUT` int(11) DEFAULT '0',
  `ascFanta_TodayVal` decimal(6,2) DEFAULT NULL,
  `ascFanta_LastACP` decimal(6,2) DEFAULT '0.00',
  `ascFanta_AvgTACP` decimal(6,2) DEFAULT '0.00',
  `ascFanta_ACPGrp` int(11) DEFAULT '0',
  `ascFanta_ACPGrpAvg` decimal(6,2) DEFAULT '0.00',
  `ascFanta_ACPGrpVal` decimal(6,2) DEFAULT '0.00',
  `ascFanta_gmPGrp` int(11) DEFAULT '0',
  `ascFanta_gmPGrpACPAvg` decimal(6,2) DEFAULT NULL,
  `ascFanta_gmPGrpACPVal` decimal(6,2) DEFAULT NULL,
  `ascFanta_LastpValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_rStatus` varchar(50) DEFAULT NULL,
  `ascFanta_lastUpDate` datetime DEFAULT NULL,
  `ascFanta_ODDate` datetime DEFAULT NULL,
  `ascFanta_TACPpVal` decimal(6,2) DEFAULT NULL,
  `ascFatna_AACPpVal` decimal(6,2) DEFAULT NULL,
  `ascFanta_TodayACPpVal` decimal(6,2) DEFAULT NULL,
  `ascFanta_pValue_Change` decimal(6,2) DEFAULT NULL,
  `ascFanta_pValue_Final` decimal(6,2) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_DailyValueRank_NBA_2018_s1`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_DailyValueRank_NBA_2018_s2` (
  `idascFanta_DailyValueRank_NBA_2018` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_mDate_est` date DEFAULT NULL,
  `ascFanta_mDate_hkt` date DEFAULT NULL,
  `ascFanta_mDate` varchar(45) DEFAULT NULL,
  `ascFanta_pID` int(11) DEFAULT NULL,
  `ascFanta_gPos` varchar(20) DEFAULT NULL,
  `ascFanta_TodayAvgACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_TACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_TodayGain` int(11) DEFAULT '0',
  `ascFanta_TodayLoss` int(11) DEFAULT '0',
  `ascFanta_TodayTTx` int(11) DEFAULT '0',
  `ascFanta_TodayTUT` int(11) DEFAULT '0',
  `ascFanta_TodayVal` decimal(6,2) DEFAULT NULL,
  `ascFanta_LastACP` decimal(6,2) DEFAULT '0.00',
  `ascFanta_AvgTACP` decimal(6,2) DEFAULT '0.00',
  `ascFanta_ACPGrp` int(11) DEFAULT '0',
  `ascFanta_ACPGrpAvg` decimal(6,2) DEFAULT '0.00',
  `ascFanta_ACPGrpVal` decimal(6,2) DEFAULT '0.00',
  `ascFanta_gmPGrp` int(11) DEFAULT '0',
  `ascFanta_gmPGrpACPAvg` decimal(6,2) DEFAULT NULL,
  `ascFanta_gmPGrpACPVal` decimal(6,2) DEFAULT NULL,
  `ascFanta_LastpValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_rStatus` varchar(50) DEFAULT NULL,
  `ascFanta_lastUpDate` datetime DEFAULT NULL,
  `ascFanta_ODDate` datetime DEFAULT NULL,
  `ascFanta_TACPpVal` decimal(6,2) DEFAULT NULL,
  `ascFatna_AACPpVal` decimal(6,2) DEFAULT NULL,
  `ascFanta_TodayACPpVal` decimal(6,2) DEFAULT NULL,
  `ascFanta_pValue_Change` decimal(6,2) DEFAULT NULL,
  `ascFanta_pValue_Final` decimal(6,2) DEFAULT NULL,
  PRIMARY KEY(`idascFanta_DailyValueRank_NBA_2018`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_GameRule` (
  `idascFanta_GameRule` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_gameName` varchar(200) DEFAULT NULL,
  `ascFanta_Parent` varchar(10) DEFAULT NULL,
  `ascFanta_gameCode` varchar(12) DEFAULT NULL,
  `ascFanta_ValueItem` varchar(50) DEFAULT NULL,
  `ascFanta_Value` decimal(5,2) DEFAULT NULL,
  `ascFanta_ValueSymbol` varchar(5) DEFAULT NULL,
  `ascFanta_Bonus` varchar(45) DEFAULT NULL,
  `ascFanta_BonusValue` int(11) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_GameRule`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_Match_NBA_2018` (
  `idascFanta_Match` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_mID` varchar(12) DEFAULT NULL,
  `ascFanta_mSource` varchar(50) DEFAULT NULL,
  `ascFanta_src_mDate` datetime DEFAULT NULL,
  `ascFanta_hkt_mDate` datetime DEFAULT NULL,
  `ascFanta_mDate` varchar(10) DEFAULT NULL,
  `ascFanta_mTime` varchar(20) DEFAULT NULL,
  `ascFanta_src_TimeZone` varchar(100) DEFAULT NULL,
  `ascFanta_src_TimeAdj` int(11) DEFAULT NULL,
  `ascFanta_mStage` varchar(5) DEFAULT NULL,
  `ascFanta_mStatus` varchar(45) DEFAULT NULL,
  `ascFanta_InsKey` varchar(36) DEFAULT NULL,
  `ascFanta_CfmKey` varchar(36) DEFAULT NULL,
  `ascFanta_mHome` varchar(100) DEFAULT NULL,
  `ascFanta_mAway` varchar(100) DEFAULT NULL,
  `ascFanta_mRegDateTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ascFanta_rActive` int(11) DEFAULT NULL COMMENT '0 = New, 1=Current Use, -9=OutDated',
  `ascFanta_rStatus` varchar(50) DEFAULT NULL,
  `ascFanta_hkt_TimeAdj` int(11) DEFAULT '8',
  PRIMARY KEY (`idascFanta_Match`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_Match_Stage` (
  `idascFanta_Match_Stage` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_LeagueName` varchar(100) DEFAULT NULL,
  `ascFanta_GameSeason` varchar(50) DEFAULT NULL,
  `ascFanta_StageName` varchar(50) DEFAULT NULL,
  `ascFanta_StageDesc` varchar(500) DEFAULT NULL,
  `ascFanta_Stage_sDate` datetime DEFAULT NULL,
  `ascFanta_Stage_eDate` datetime DEFAULT NULL,
  `ascFanta_rStatus` varchar(50) DEFAULT NULL,
  `ascFanta_rActive` int(11) DEFAULT NULL,
  `ascFanta_rRegDateTime` datetime DEFAULT NULL,
  PRIMARY KEY (`idascFanta_Match_Stage`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_PlayerMaster_NBA_2018_s1` (
  `idascFanta_PlayerMaster` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_pSource` varchar(50) DEFAULT NULL,
  `ascFanta_pID` int(11) DEFAULT NULL,
  `ascFanta_pID_ESPN` int(11) DEFAULT NULL,
  `ascFanta_gLName` varchar(200) DEFAULT NULL,
  `ascFanta_pFName` varchar(200) DEFAULT NULL,
  `ascFanta_pLName` varchar(200) DEFAULT NULL,
  `ascFanta_gFName` varchar(200) DEFAULT NULL,
  `ascFanta_gFullName` varchar(100) DEFAULT NULL,
  `ascFanta_pPos` varchar(20) DEFAULT NULL,
  `ascFanta_gPos` varchar(20) DEFAULT NULL,
  `ascFanta_pAge` int(11) DEFAULT NULL,
  `ascFanta_pDOB` varchar(20) DEFAULT NULL,
  `ascFanta_pHt` varchar(45) DEFAULT NULL,
  `ascFanta_pWt` varchar(45) DEFAULT NULL,
  `ascFanta_pProYr` int(11) DEFAULT NULL,
  `ascFanta_pColleage` varchar(200) DEFAULT NULL,
  `ascFanta_pSalary` varchar(20) DEFAULT NULL,
  `ascFanta_gInitValue` decimal(5,2) DEFAULT NULL,
  `ascFanta_pTeam` varchar(200) DEFAULT NULL,
  `ascFanta_pRank` varchar(20) DEFAULT NULL,
  `ascFanta_pRegDateTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ascFanta_rActive` int(11) DEFAULT NULL,
  `ascFanta_rStatus` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_PlayerMaster`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_PlayerMaster_NBA_2018_s2` (
  `idascFanta_PlayerMaster` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_pSource` varchar(50) DEFAULT NULL,
  `ascFanta_pID` int(11) DEFAULT NULL,
  `ascFanta_pID_ESPN` int(11) DEFAULT NULL,
  `ascFanta_gLName` varchar(200) DEFAULT NULL,
  `ascFanta_pFName` varchar(200) DEFAULT NULL,
  `ascFanta_pLName` varchar(200) DEFAULT NULL,
  `ascFanta_gFName` varchar(200) DEFAULT NULL,
  `ascFanta_gFullName` varchar(100) DEFAULT NULL,
  `ascFanta_pPos` varchar(20) DEFAULT NULL,
  `ascFanta_gPos` varchar(20) DEFAULT NULL,
  `ascFanta_pAge` int(11) DEFAULT NULL,
  `ascFanta_pDOB` varchar(20) DEFAULT NULL,
  `ascFanta_pHt` varchar(45) DEFAULT NULL,
  `ascFanta_pWt` varchar(45) DEFAULT NULL,
  `ascFanta_pProYr` int(11) DEFAULT NULL,
  `ascFanta_pColleage` varchar(200) DEFAULT NULL,
  `ascFanta_pSalary` varchar(20) DEFAULT NULL,
  `ascFanta_gInitValue` decimal(5,2) DEFAULT NULL,
  `ascFanta_pTeam` varchar(200) DEFAULT NULL,
  `ascFanta_pRank` varchar(20) DEFAULT NULL,
  `ascFanta_pRegDateTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ascFanta_rActive` int(11) DEFAULT NULL,
  `ascFanta_rStatus` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_PlayerMaster`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_PlayerStat_NBA_2018_s1` (
  `idascFanta_PlayerStat_NBA_2018_s1` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_sMatchID` varchar(45) DEFAULT NULL,
  `ascFanta_personId` int(11) DEFAULT NULL,
  `ascFanta_sMatchDate` datetime DEFAULT NULL,
  `ascFanta_min` varchar(10) DEFAULT NULL,
  `ascFanta_assists` int(11) DEFAULT '0',
  `ascFanta_blocks` int(11) DEFAULT '0',
  `ascFanta_defReb` int(11) DEFAULT '0',
  `ascFanta_fga` int(11) DEFAULT '0',
  `ascFanta_fgm` int(11) DEFAULT '0',
  `ascFanta_fgs` int(11) DEFAULT '0',
  `ascFanta_fgp` int(11) DEFAULT '0',
  `ascFanta_fta` int(11) DEFAULT '0',
  `ascFanta_ftm` int(11) DEFAULT '0',
  `ascFanta_fts` int(11) DEFAULT '0',
  `ascFanta_ftp` int(11) DEFAULT '0',
  `ascFanta_offReb` int(11) DEFAULT '0',
  `ascFanta_totReb` int(11) DEFAULT '0',
  `ascFanta_pFouls` int(11) DEFAULT '0',
  `ascFanta_points` int(11) DEFAULT '0',
  `ascFanta_plusMinus` int(11) DEFAULT NULL,
  `ascFanta_steals` int(11) DEFAULT '0',
  `ascFanta_teamId` varchar(20) DEFAULT NULL,
  `ascFanta_turnovers` int(11) DEFAULT NULL,
  `ascFanta_sTimeStamp` datetime DEFAULT NULL,
  `ascFanta_ACP` decimal(5,2) DEFAULT NULL,
  `ascFanta_Bonus` varchar(10) DEFAULT NULL,
  `ascFanta_BonusValue` int(11) DEFAULT '0',
  `ascFanta_TACP` decimal(5,2) DEFAULT '0.00',
  `ascFanta_InsKey` varchar(36) DEFAULT NULL,
  `ascFanta_CfmKey` varchar(36) DEFAULT NULL,
  `ascFanta_DRankKey` varchar(36) DEFAULT NULL,
  `ascFanta_rStatus` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_PlayerStat_NBA_2018_s1`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_PlayerStat_NBA_2018_s2` (
  `idascFanta_PlayerStat_NBA_2018` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_sMatchID` varchar(45) DEFAULT NULL,
  `ascFanta_personId` int(11) DEFAULT NULL,
  `ascFanta_sMatchDate` datetime DEFAULT NULL,
  `ascFanta_min` varchar(10) DEFAULT NULL,
  `ascFanta_assists` int(11) DEFAULT '0',
  `ascFanta_blocks` int(11) DEFAULT '0',
  `ascFanta_defReb` int(11) DEFAULT '0',
  `ascFanta_fga` int(11) DEFAULT '0',
  `ascFanta_fgm` int(11) DEFAULT '0',
  `ascFanta_fgs` int(11) DEFAULT '0',
  `ascFanta_fgp` int(11) DEFAULT '0',
  `ascFanta_fta` int(11) DEFAULT '0',
  `ascFanta_ftm` int(11) DEFAULT '0',
  `ascFanta_fts` int(11) DEFAULT '0',
  `ascFanta_ftp` int(11) DEFAULT '0',
  `ascFanta_offReb` int(11) DEFAULT '0',
  `ascFanta_totReb` int(11) DEFAULT '0',
  `ascFanta_pFouls` int(11) DEFAULT '0',
  `ascFanta_points` int(11) DEFAULT '0',
  `ascFanta_plusMinus` int(11) DEFAULT NULL,
  `ascFanta_steals` int(11) DEFAULT '0',
  `ascFanta_teamId` varchar(20) DEFAULT NULL,
  `ascFanta_turnovers` int(11) DEFAULT NULL,
  `ascFanta_sTimeStamp` datetime DEFAULT NULL,
  `ascFanta_ACP` decimal(5,2) DEFAULT NULL,
  `ascFanta_Bonus` varchar(10) DEFAULT NULL,
  `ascFanta_BonusValue` int(11) DEFAULT '0',
  `ascFanta_TACP` decimal(5,2) DEFAULT '0.00',
  `ascFanta_InsKey` varchar(36) DEFAULT NULL,
  `ascFanta_CfmKey` varchar(36) DEFAULT NULL,
  `ascFanta_DRankKey` varchar(36) DEFAULT NULL,
  `ascFanta_rStatus` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_PlayerStat_NBA_2018`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_PlayerValue_NBA_2018_s1` (
  `idascFanta_PlayerValue` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_pID` int(11) DEFAULT NULL,
  `ascFanta_mDate` varchar(45) DEFAULT NULL,
  `ascFanta_pPos` varchar(10) DEFAULT NULL,
  `ascFanta_gPos` varchar(10) DEFAULT NULL,
  `ascFanta_gInitValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_gLastValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_gTTLACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_gLastACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_gNowNOH` int(11) DEFAULT NULL,
  `ascFanta_gLastNOH` int(11) DEFAULT NULL,
  `ascFanta_gNowValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_gChgValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_lastVal_Key` varchar(45) DEFAULT NULL,
  `ascFanta_newVal_Key` varchar(45) DEFAULT NULL,
  `ascFanta_Active` bit(1) DEFAULT NULL,
  `ascFanta_Status` int(11) DEFAULT NULL,
  `ascFanta_RegDate` timestamp NULL DEFAULT NULL,
  `ascFanta_rStatus` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_PlayerValue`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_PlayerValue_NBA_2018_s2` (
  `idascFanta_PlayerValue` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_pID` int(11) DEFAULT NULL,
  `ascFanta_mDate` varchar(45) DEFAULT NULL,
  `ascFanta_pPos` varchar(10) DEFAULT NULL,
  `ascFanta_gPos` varchar(10) DEFAULT NULL,
  `ascFanta_gInitValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_gLastValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_gTTLACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_gLastACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_gNowNOH` int(11) DEFAULT NULL,
  `ascFanta_gLastNOH` int(11) DEFAULT NULL,
  `ascFanta_gNowValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_gChgValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_lastVal_Key` varchar(45) DEFAULT NULL,
  `ascFanta_newVal_Key` varchar(45) DEFAULT NULL,
  `ascFanta_Active` bit(1) DEFAULT NULL,
  `ascFanta_Status` int(11) DEFAULT NULL,
  `ascFanta_RegDate` timestamp NULL DEFAULT NULL,
  `ascFanta_rStatus` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_PlayerValue`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_Team_NBA_2018` (
  `idascFanta_Team` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_tID` varchar(20) DEFAULT NULL,
  `ascFanta_tCity` varchar(200) DEFAULT NULL,
  `ascFanta_tAbbr` varchar(5) DEFAULT NULL,
  `ascFanta_tName` varchar(200) DEFAULT NULL,
  `ascFanta_tCode` varchar(200) DEFAULT NULL,
  `ascFanta_tDiv` varchar(200) DEFAULT NULL,
  `ascFanta_tConf` varchar(200) DEFAULT NULL,
  `ascFanta_rStatus` varchar(20) DEFAULT NULL,
  `ascFanta_tSource` varchar(50) DEFAULT NULL,
  `ascFanta_tNickName` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_Team`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_UserTeam_Master` (
  `idascUserTeam_Master` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_UserName` varchar(200) DEFAULT NULL,
  `ascFanta_UserIMEI` varchar(20) DEFAULT NULL,
  `ascFanta_TeamName` varchar(200) DEFAULT NULL,
  `ascFanta_Group` varchar(200) DEFAULT NULL,
  `ascFanta_GroupKey` varchar(36) DEFAULT NULL,
  `ascFanta_TeamID` varchar(36) DEFAULT NULL,
  `ascFanta_League` varchar(45) DEFAULT NULL,
  `ascFanta_seasonYear` varchar(45) DEFAULT NULL,
  `ascFanta_seasonStage` varchar(45) DEFAULT NULL,
  `ascFanta_RegDate` datetime DEFAULT NULL,
  `ascFanta_lastUpDate` datetime DEFAULT NULL,
  `ascFanta_rActive` int(11) DEFAULT NULL,
  `ascFanta_rStatus` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idascUserTeam_Master`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Keep User vs FantaZ Team table. A user can open multiple FzTeam by Stage, Season and League';


CREATE TABLE `ascFanta_UTRoster_DailyLog_NBA_2018_s1` (
  `idascFanta_UTRoster_DailyLog_NBA` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_TeamID` varchar(45) DEFAULT NULL,
  `ascFanta_TeamName` varchar(100) DEFAULT NULL,
  `ascFanta_TeamValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_pID_G1` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_G1` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_G1` varchar(45) DEFAULT NULL,
  `ascFanta_pID_G2` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_G2` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_G2` varchar(45) DEFAULT NULL,
  `ascFanta_pID_F1` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_F1` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_F1` varchar(45) DEFAULT NULL,
  `ascFanta_pID_F2` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_F2` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_F2` varchar(45) DEFAULT NULL,
  `ascFanta_pID_C1` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_C1` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_C1` varchar(45) DEFAULT NULL,
  `ascFanta_pID_B1` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_B1` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_B1` varchar(45) DEFAULT NULL,
  `ascFanta_LogDate` varchar(45) DEFAULT NULL,
  `ascFanta_rStatus` varchar(45) DEFAULT NULL,
  `ascFanta_Active` int(11) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_UTRoster_DailyLog_NBA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_UTRoster_DailyLog_NBA_2018_s2` (
  `idascFanta_UTRoster_DailyLog_NBA` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_TeamID` varchar(45) DEFAULT NULL,
  `ascFanta_TeamName` varchar(100) DEFAULT NULL,
  `ascFanta_Group` varchar(200) DEFAULT NULL,
  `ascFanta_GroupKey` varchar(45) DEFAULT NULL,
  `ascFanta_TeamValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_TeamValueRemain` decimal(6,2) DEFAULT NULL,
  `ascFanta_pID_G1` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_G1` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_G1` varchar(45) DEFAULT NULL,
  `ascFanta_G1_ACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_pID_G2` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_G2` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_G2` varchar(45) DEFAULT NULL,
  `ascFanta_G2_ACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_pID_F1` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_F1` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_F1` varchar(45) DEFAULT NULL,
  `ascFanta_F1_ACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_pID_F2` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_F2` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_F2` varchar(45) DEFAULT NULL,
  `ascFanta_F2_ACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_pID_C1` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_C1` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_C1` varchar(45) DEFAULT NULL,
  `ascFanta_C1_ACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_pID_B1` varchar(45) DEFAULT NULL,
  `ascFanta_trKey_B1` varchar(45) DEFAULT NULL,
  `ascFanta_pVal_B1` varchar(45) DEFAULT NULL,
  `ascFanta_B1_ACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_LogDate` varchar(45) DEFAULT NULL,
  `ascFanta_TodayTACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_rStatus` varchar(45) DEFAULT NULL,
  `ascFanta_Active` int(11) DEFAULT NULL,
  `ascFanta_LogKey` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_UTRoster_DailyLog_NBA`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_UTRoster_DailyRank_NBA_2018_s2` (
  `idascFanta_UTRoster_DailyRank_NBA_2018_s2` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_TeamID` varchar(45) DEFAULT NULL,
  `ascFanta_TeamName` varchar(200) DEFAULT NULL,
  `ascFanta_Group` varchar(200) DEFAULT NULL,
  `ascFanta_GroupKey` varchar(45) DEFAULT NULL,
  `ascFanta_TACP` decimal(6,2) DEFAULT NULL,
  `ascFanta_TeamValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_gmDate` varchar(45) DEFAULT NULL,
  `ascFanta_TimeStamp` datetime DEFAULT NULL,
  `ascFanta_LogKey` varchar(45) DEFAULT NULL,
  `ascFanta_rStatus` varchar(45) DEFAULT NULL,
  `ascFanta_lastRank` int(11) DEFAULT NULL,
  `ascFanta_nowRank` int(11) DEFAULT NULL,
  `ascFanta_lastUTRank` int(11) DEFAULT NULL,
  `ascFanta_nowUTRank` int(11) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_UTRoster_DailyRank_NBA_2018_s2`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_UTRoster_Master_NBA_2018_s1` (
  `idascFanta_UTRoster_Master_NBA_2018_s1` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_UserFBID` varchar(100) DEFAULT NULL,
  `ascFanta_UserIMEI` varchar(100) DEFAULT NULL,
  `ascFanta_TeamID` varchar(36) DEFAULT NULL,
  `ascFanta_TeamName` varchar(100) DEFAULT NULL,
  `ascFanta_RegDate` datetime DEFAULT NULL,
  `ascFanta_LastUP` datetime DEFAULT NULL,
  `ascFanta_pID_G1` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_G1` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_G1` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_G1` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_G1` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_G1` date DEFAULT NULL,
  `ascFanta_trKey_G1` varchar(45) DEFAULT NULL,
  `ascFanta_pID_G2` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_G2` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_G2` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_G2` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_G2` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_G2` date DEFAULT NULL,
  `ascFanta_trKey_G2` varchar(45) DEFAULT NULL,
  `ascFanta_pID_F1` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_F1` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_F1` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_F1` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_F1` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_F1` date DEFAULT NULL,
  `ascFanta_trKey_F1` varchar(45) DEFAULT NULL,
  `ascFanta_pID_F2` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_F2` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_F2` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_F2` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_F2` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_F2` date DEFAULT NULL,
  `ascFanta_trKey_F2` varchar(45) DEFAULT NULL,
  `ascFanta_pID_C1` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_C1` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_C1` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_C1` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_C1` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_C1` date DEFAULT NULL,
  `ascFanta_trKey_C1` varchar(45) DEFAULT NULL,
  `ascFanta_pID_B1` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_B1` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_B1` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_B1` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_B1` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_B1` date DEFAULT NULL,
  `ascFanta_trKey_B1` varchar(45) DEFAULT NULL,
  `ascFanta_gValueGain` decimal(5,2) DEFAULT NULL,
  `ascFanta_gValueUsed` decimal(5,2) DEFAULT NULL,
  `ascFanta_gTradeGain` int(11) DEFAULT NULL,
  `ascFanta_gTradeUsed` int(11) DEFAULT NULL,
  `ascFanta_gValueRemain` decimal(5,2) DEFAULT NULL,
  `ascFanta_gValueBuyCount` int(11) DEFAULT NULL,
  `ascFanta_gTradeRemain` int(11) DEFAULT NULL,
  `ascFanta_gTradeBuyCount` int(11) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_UTRoster_Master_NBA_2018_s1`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_UTRoster_Master_NBA_2018_s2` (
  `idascFanta_UTRoster_Master_NBA_2018` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_UserFBID` varchar(100) DEFAULT NULL,
  `ascFanta_UserIMEI` varchar(100) DEFAULT NULL,
  `ascFanta_TeamID` varchar(36) DEFAULT NULL,
  `ascFanta_TeamName` varchar(100) DEFAULT NULL,
  `ascFanta_Group` varchar(200) DEFAULT NULL,
  `ascFanta_GroupKey` varchar(45) DEFAULT NULL,
  `ascFanta_RegDate` datetime DEFAULT NULL,
  `ascFanta_LastUP` datetime DEFAULT NULL,
  `ascFanta_pID_G1` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_G1` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_G1` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_G1` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_G1` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_G1` date DEFAULT NULL,
  `ascFanta_trKey_G1` varchar(45) DEFAULT NULL,
  `ascFanta_pID_G2` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_G2` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_G2` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_G2` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_G2` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_G2` date DEFAULT NULL,
  `ascFanta_trKey_G2` varchar(45) DEFAULT NULL,
  `ascFanta_pID_F1` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_F1` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_F1` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_F1` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_F1` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_F1` date DEFAULT NULL,
  `ascFanta_trKey_F1` varchar(45) DEFAULT NULL,
  `ascFanta_pID_F2` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_F2` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_F2` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_F2` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_F2` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_F2` date DEFAULT NULL,
  `ascFanta_trKey_F2` varchar(45) DEFAULT NULL,
  `ascFanta_pID_C1` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_C1` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_C1` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_C1` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_C1` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_C1` date DEFAULT NULL,
  `ascFanta_trKey_C1` varchar(45) DEFAULT NULL,
  `ascFanta_pID_B1` varchar(10) DEFAULT NULL,
  `ascFanta_pPos_B1` varchar(5) DEFAULT NULL,
  `ascFanta_pSName_B1` varchar(50) DEFAULT NULL,
  `ascFanta_pLName_B1` varchar(50) DEFAULT NULL,
  `ascFanta_pValue_B1` decimal(5,2) DEFAULT NULL,
  `ascFanta_pBuyDate_B1` date DEFAULT NULL,
  `ascFanta_trKey_B1` varchar(45) DEFAULT NULL,
  `ascFanta_gValueGain` decimal(5,2) DEFAULT NULL,
  `ascFanta_gValueUsed` decimal(5,2) DEFAULT NULL,
  `ascFanta_gTradeGain` int(11) DEFAULT NULL,
  `ascFanta_gTradeUsed` int(11) DEFAULT NULL,
  `ascFanta_gValueRemain` decimal(5,2) DEFAULT NULL,
  `ascFanta_gValueBuyCount` int(11) DEFAULT NULL,
  `ascFanta_gTradeRemain` int(11) DEFAULT NULL,
  `ascFanta_gTradeBuyCount` int(11) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_UTRoster_Master_NBA_2018`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_UTRoster_TX_NBA_2018_s1` (
  `idascFanta_UserRoster` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_TeamID` varchar(45) DEFAULT NULL,
  `ascFanta_TeamName` varchar(1) DEFAULT NULL,
  `ascFanta_RegDate` varchar(45) DEFAULT NULL,
  `ascFanta_XchPos` varchar(10) DEFAULT NULL,
  `ascFanta_fmPIayerID` varchar(45) DEFAULT NULL,
  `ascFanta_toPlayerID` varchar(45) DEFAULT NULL,
  `ascFanta_XchType` varchar(45) DEFAULT NULL COMMENT 'Buy or Sell',
  `ascFanta_TradeToken` int(11) DEFAULT NULL,
  `ascFanta_TokenKey` varchar(45) DEFAULT NULL,
  `ascFanta_TradeTimestamp` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_UserRoster`),
  UNIQUE KEY `idascFanta_UserRoster_UNIQUE` (`idascFanta_UserRoster`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascFanta_UTRoster_TX_NBA_2018_s2` (
  `idascFanta_UserRoster` int(11) NOT NULL AUTO_INCREMENT,
  `ascFanta_TeamID` varchar(45) DEFAULT NULL,
  `ascFanta_TeamName` varchar(100) DEFAULT NULL,
  `ascFanta_Group` varchar(200) DEFAULT NULL,
  `ascFanta_GroupKey` varchar(45) DEFAULT NULL,
  `ascFanta_TxGmDate` varchar(45) DEFAULT NULL,
  `ascFanta_TxTimestamp` datetime DEFAULT NULL,
  `ascFanta_XchPos` varchar(10) DEFAULT NULL,
  `ascFanta_fmPlayerID` varchar(45) DEFAULT NULL,
  `ascFanta_toPlayerID` varchar(45) DEFAULT NULL,
  `ascFanta_XchType` varchar(45) DEFAULT NULL COMMENT 'Buy or Sell',
  `ascFanta_TradeToken` int(11) DEFAULT NULL,
  `ascFanta_TradeTokenKey` varchar(45) DEFAULT NULL,
  `ascFanta_fmPlayerValue` varchar(45) DEFAULT NULL,
  `ascFanta_fmPlayerValueKey` varchar(45) DEFAULT NULL,
  `ascFanta_toPlayerValue` varchar(45) DEFAULT NULL,
  `ascFanta_toPlayerValueKey` varchar(45) DEFAULT NULL,
  `ascFanta_fmUTValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_toUTValue` decimal(6,2) DEFAULT NULL,
  `ascFanta_UTValueChange` decimal(6,2) DEFAULT NULL,
  `ascFanta_TxKey` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idascFanta_UserRoster`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascSchedule_Log` (
  `idascSchedule_Log` int(11) NOT NULL AUTO_INCREMENT,
  `ScheduleTime` varchar(50) DEFAULT NULL,
  `ActionTime` varchar(50) DEFAULT NULL,
  `ActionName` varchar(200) DEFAULT NULL,
  `ActionResult` varchar(500) DEFAULT NULL,
  `ActionIP` varchar(45) DEFAULT NULL,
  `ActiveSeason` varchar(45) DEFAULT NULL,
  `ActiveStage` varchar(45) DEFAULT NULL,
  `ActiveLeague` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idascSchedule_Log`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascUser_Log` (
  `idascUser_Log` int(11) NOT NULL AUTO_INCREMENT,
  `asc_LastLoginName` varchar(45) DEFAULT NULL,
  `asc_LastTeamName` varchar(200) DEFAULT NULL,
  `asc_LastKey` varchar(45) DEFAULT NULL,
  `asc_LastAction` varchar(45) DEFAULT NULL,
  `asc_LastActionDT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `asc_LastApp` varchar(45) DEFAULT NULL,
  `asc_LastIP` varchar(45) DEFAULT NULL,
  `asc_LastPlatform` varchar(500) DEFAULT NULL,
  `asc_LastPlatformVer` varchar(500) DEFAULT NULL,
  `asc_LastUUID` varchar(500) DEFAULT NULL,
  `asc_LastMfger` varchar(500) DEFAULT NULL,
  `asc_LastIsVM` varchar(45) DEFAULT NULL,
  `asc_LastLocation` varchar(500) DEFAULT NULL,
  `asc_Active` bit(1) DEFAULT NULL,
  PRIMARY KEY (`idascUser_Log`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `ascUsers` (
  `idascUser` int(11) NOT NULL AUTO_INCREMENT,
  `asc_userID` varchar(500) DEFAULT NULL,
  `ascFanta_TeamName` varchar(45) DEFAULT NULL,
  `asc_passWd` varchar(45) DEFAULT NULL,
  `asc_userName` varchar(500) DEFAULT NULL,
  `asc_userKey` varchar(45) DEFAULT NULL,
  `asc_userRegDT` datetime DEFAULT NULL,
  `asc_ACVerified` bit(1) DEFAULT NULL,
  `asc_userVerifyDT` datetime DEFAULT NULL,
  `asc_forgetWd` int(11) DEFAULT NULL,
  `asc_userNation` varchar(45) DEFAULT NULL,
  `asc_userDOB` date DEFAULT NULL,
  `asc_userGender` varchar(1) DEFAULT NULL,
  `asc_userLiving` varchar(500) DEFAULT NULL,
  `asc_userSchool` varchar(500) DEFAULT NULL,
  `asc_userGrade` varchar(20) DEFAULT NULL,
  `asc_userTerms` bit(1) DEFAULT NULL,
  `asc_userAdsRemove` bit(1) DEFAULT NULL,
  `asc_rActive` int(11) DEFAULT NULL,
  `asc_rStatus` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idascUser`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;





