INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (1,'new york','knicks','atlantic','east','NY');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (2,'brooklyn','nets','atlantic','east','BKN');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (3,'boston','celtics','atlantic','east','BOS');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (4,'philadelphia','76ers','atlantic','east','PHI');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (5,'toronto','raptors','atlantic','east','TOR');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (6,'indiana','pacers','central','east','IND');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (7,'chicago','bulls','central','east','CHI');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (8,'milwaukee','bucks','central','east','MIL');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (9,'detroit','pistons','central','east','DET');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (10,'cleveland','cavaliers','central','east','CLE');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (11,'miami','heat','southeast','east','MIA');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (12,'atlanta','hawks','southeast','east','ATL');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (13,'washington','wizards','southeast','east','WSH');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (14,'charlotte','hornets','southeast','east','CHA');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (15,'orlando','magic','southeast','east','ORL');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (16,'oklahoma city','thunder','northwest','west','OKC');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (17,'denver','muggets','northwest','west','DEN');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (18,'utah','jazz','northwest','west','UTAH');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (19,'portland','trail blazers','northwest','west','POR');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (20,'minnesota','timberwolves','northwest','west','MIN');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (21,'los angeles','clippers','pacific','west','LAC');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (22,'golden state','warriors','pacific','west','GS');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (23,'los angeles','lakers','pacific','west','LAL');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (24,'sacramento','kings','pacific','west','SAC');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (25,'phoenix','suns','pacific','west','PHX');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (26,'san antonio','spurs','southwest','west','SA');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (27,'memphis','grizzlies','southwest','west','MEM');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (28,'houston','rockets','southwest','west','HOU');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (29,'dallas','mavericks','southwest','west','DAL');
INSERT INTO `ascFanta_Team_NBA_2018` (`idascFanta_Team`,`ascFanta_tCity`,`ascFanta_tName`,`ascFanta_tDiv`,`ascFanta_tConf`,`ascFanta_tCode`) VALUES (30,'new orleans','pelicans','southwest','west','NO');
